FROM qdrant/qdrant:v1.1.1

VOLUME /qdrant/storage
VOLUME /qdrant/config

EXPOSE 6333
EXPOSE 6334

# Entferne den COPY-Befehl, da wir das Volume mounten

CMD ["./qdrant", "--config-path", "/qdrant/config/config.yaml"]
